
:-assert(wm(scale(0, aminor))).
:-assert(wm(scale(0, cmajor))).
:-assert(wm(scale(2, aminor))).
:-assert(wm(scale(2, cmajor))).
:-assert(wm(scale(4, aminor))).
:-assert(wm(scale(4, cmajor))).
:-assert(wm(scale(5, aminor))).
:-assert(wm(scale(5, cmajor))).
:-assert(wm(scale(7, cmajor))).
:-assert(wm(scale(8, aminor))).
:-assert(wm(scale(9, aminor))).
:-assert(wm(scale(9, cmajor))).
:-assert(wm(scale(11, aminor))).
:-assert(wm(scale(11, cmajor))).
:-assert(wm(scale(12, aminor))).
:-assert(wm(scale(12, cmajor))).

:-assert(wm(scale(1, asminor))).
:-assert(wm(scale(1, csmajor))).
:-assert(wm(scale(3, asminor))).
:-assert(wm(scale(3, csmajor))).
:-assert(wm(scale(5, asminor))).
:-assert(wm(scale(5, csmajor))).
:-assert(wm(scale(6, asminor))).
:-assert(wm(scale(6, csmajor))).
:-assert(wm(scale(8, csmajor))).
:-assert(wm(scale(9, asminor))).
:-assert(wm(scale(10, asminor))).
:-assert(wm(scale(10, csmajor))).
:-assert(wm(scale(12, asminor))).
:-assert(wm(scale(12, csmajor))).
:-assert(wm(scale(13, asminor))).
:-assert(wm(scale(13, csmajor))).

:-assert(wm(scale(2, bminor))).
:-assert(wm(scale(2, dmajor))).
:-assert(wm(scale(4, bminor))).
:-assert(wm(scale(4, dmajor))).
:-assert(wm(scale(6, bminor))).
:-assert(wm(scale(6, dmajor))).
:-assert(wm(scale(7, bminor))).
:-assert(wm(scale(7, dmajor))).
:-assert(wm(scale(9, dmajor))).
:-assert(wm(scale(10, bminor))).
:-assert(wm(scale(11, bminor))).
:-assert(wm(scale(11, dmajor))).
:-assert(wm(scale(13, bminor))).
:-assert(wm(scale(13, dmajor))).
:-assert(wm(scale(14, bminor))).
:-assert(wm(scale(14, dmajor))).

:-assert(wm(scale(3, csminor))).
:-assert(wm(scale(3, ebmajor))).
:-assert(wm(scale(5, csminor))).
:-assert(wm(scale(5, ebmajor))).
:-assert(wm(scale(7, csminor))).
:-assert(wm(scale(7, ebmajor))).
:-assert(wm(scale(8, csminor))).
:-assert(wm(scale(8, ebmajor))).
:-assert(wm(scale(10, ebmajor))).
:-assert(wm(scale(11, csminor))).
:-assert(wm(scale(12, csminor))).
:-assert(wm(scale(12, ebmajor))).
:-assert(wm(scale(14, csminor))).
:-assert(wm(scale(14, ebmajor))).
:-assert(wm(scale(15, csminor))).
:-assert(wm(scale(15, ebmajor))).

